services:
  - type: static
    name: frontend-client
    rootDir: client
    buildCommand: npm ci && npm run build
    staticPublishPath: build

  - type: web
    name: frontend-server
    env: node
    rootDir: server
    buildCommand: npm ci
    startCommand: npm start
